name: Build Action Server

on:
  workflow_dispatch:

jobs:
  lint-testing:
    name: Code Formatting Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.15
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements-dev.txt
    - name: Code Formatting Tests
      working-directory: ${{ github.workspace }}
      run: |
        make lint
  # type-testing:
  #   name: Type Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up Python 3.10
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: 3.10.15
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install -U pip
  #       pip install -r requirements-dev.txt
  #   - name: Type Checking
  #     working-directory: ${{ github.workspace }}
  #     run: |
  #       make types

  docker:
    name: Build Action Server Docker Image
    runs-on: ubuntu-latest
    needs: [lint-testing]
    # needs: [lint-testing, type-testing]
    env:
      DOCKERHUB_USERNAME: stephens
    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@v4
      - name: Build Actions Server Image
        uses: RasaHQ/rasa-action-server-gha@main
        with:
          actions_directory: 'actions'
          # requirements_file: 'actions/requirements-actions.txt'
          docker_registry_login: ${{ env.DOCKERHUB_USERNAME }}
          docker_registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          docker_image_name: 'stephens/action-server-example'
          docker_image_tag: 'latest'
          rasa_sdk_version: '3.10.1'
