name: Test & Train Model
on:
  push:
  workflow_dispatch:
# on:
#   pull_request:
#     paths-ignore:
#     - "README.md"
#     - "Makefile"
#     - "Dockerfile"

jobs:
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    # needs: [lint-testing, type-testing]
    steps:
      - uses: actions/checkout@v4
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: set_training
        if: |
            contains(  steps.files.outputs.all, 'data/' )
            || contains(  steps.files.outputs.all, 'config.yml' )
        run: echo "RUN_TRAINING=true" >> $GITHUB_ENV
      - name: Rasa Train and Test GitHub Action
        # if: env.RUN_TRAINING == 'true'
        uses: RasaHQ/rasa-train-test-gha@rasa-pro-license
        with:
          rasa_image: 'rasa/rasa-pro:3.10.12'
          train_args: '--domain domain'
          # rasa_version: '3.10.12' 
          test_type: none
          data_validate: false
          cross_validation: false
          publish_summary: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          rasa_pro_license: ${{ secrets.RASA_PRO_LICENSE }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
      - name: Upload model
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@main
        with:
          name: model
          path: models
